spring:
  thymeleaf:
    cache: false #模板使用启用缓存，调试的时候设置false比较好
    encoding: UTF-8 #模板编码
    mode: HTML5
    prefix: classpath:/templates/ #指定模板存放路径
    suffix: .html #指定模板后缀
    check-template-location: true #检查模板位置是否存在


