server:
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    #日期类型格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      #格式化输出，通常为了节省网络流量设置为false。因为格式化之后会带有缩进，方便阅读。
#      indent_output: false
#      #某些类对象无法序列化的时候，是否报错
#      fail_on_empty_beans: false
#    #设置空如何序列化，见下文代码方式详解
#    defaultPropertyInclusion: NON_EMPTY
#    deserialization:
#      #json对象中有不存在的属性时候，是否报错
#      fail_on_unknown_properties: false
#    parser:
#      #允许出现转义字符和特殊字符
#      allow_unquoted_control_chars: true
#      #可以允许单引号
#      allow_single_quotes: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
